Student.create(name: "Haruki", discipline: "Biochemistry")
Student.create(name: "Prisha", discipline: "Plant Science")
Student.create(name: "Walter", discipline: "Molecular Biology")
Student.create(name: "Pinar", discipline: "Cancer Research")
Student.create(name: "Minjun", discipline: "Microbiology")
Student.create(name: "Ahmet", discipline: "Genetics")
Student.create(name: "Mackenzie", discipline: "Neuroscience")

PrincipalInvestigator.create(name: "Dr. Harper", discipline: "Biochemistry")
PrincipalInvestigator.create(name: "Dr. Cushman", discipline: "Plant Science")
PrincipalInvestigator.create(name: "Dr. Conlon", discipline: "Molecular Biology")
PrincipalInvestigator.create(name: "Dr. Bilgi", discipline: "Cancer Research")
PrincipalInvestigator.create(name: "Dr. Shintani", discipline: "Microbiology")
PrincipalInvestigator.create(name: "Dr. Schooley", discipline: "Genetics")
PrincipalInvestigator.create(name: "Dr. Conlon", discipline: "Neuroscience")

Project.create(student_id: Student.all.sample.id, principal_investigator_id: PrincipalInvestigator.all.sample.id, name: "Enhancing Crop Growth", grant_amount: 5, grant_type: "NIH")
Project.create(student_id: Student.all.sample.id, principal_investigator_id: PrincipalInvestigator.all.sample.id, name: "Photosyntetic Efficiency", grant_amount: 8, grant_type: "DOE")
Project.create(student_id: Student.all.sample.id, principal_investigator_id: PrincipalInvestigator.all.sample.id, name: "Biofuels", grant_amount: 20, grant_type: "NSF")
Project.create(student_id: Student.all.sample.id, principal_investigator_id: PrincipalInvestigator.all.sample.id, name: "DNA Repair", grant_amount: 13, grant_type: "NIH")
Project.create(student_id: Student.all.sample.id, principal_investigator_id: PrincipalInvestigator.all.sample.id, name: "Autophagy", grant_amount: 9, grant_type: "NSF")
Project.create(student_id: Student.all.sample.id, principal_investigator_id: PrincipalInvestigator.all.sample.id, name: "CRISPR", grant_amount: 14, grant_type: "NIH")
Project.create(student_id: Student.all.sample.id, principal_investigator_id: PrincipalInvestigator.all.sample.id, name: "Circadian Clock", grant_amount: 10, grant_type: "Gates Foundation")